[colors.bright]
black = "#808080"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#B9CA4A"
magenta = "#C678DD"
red = "#FF6C6B"
white = "#FFFFFF"
yellow = "#F0C674"

[colors.normal]
black = "#1E1E1E"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
magenta = "#C678DD"
red = "#F44747"
white = "#F5F5F5"
yellow = "#E5C07B"

[colors.primary]
background = "#161616"
foreground = "#D0D0D0"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

#[window.padding]
#x = 5 
#y = 5

[window.dimensions]
columns = 120
lines = 30
